  fe[m
  feature/ads[m
  feature/auth[m
  feature/booking[m
  feature/bookingemail[m
  feature/change-avt[m
  feature/change-password[m
  feature/create-event[m
  feature/edit-profile[m
  feature/flyway[m
* [32mfeature/interface[m
  feature/login-via-google[m
  feature/qrCode[m
  feature/recommend[m
  feature/search[m
  feature/voucher[m
  feature/wishlist[m
  feature/withdraw[m
  features/authorized[m
  fix/change-password[m
  fix/conflict[m
  fix/editevent[m
  fix/header[m
  fix/home[m
  fix/register-organizer[m
  fix/role[m
  fix/roles[m
  fix/statistic[m
  main[m
